# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_passwordexpiry_passwordhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordhistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
