# Generated by Django 2.1.2 on 2018-10-17 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20170416_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailaddress',
            old_name='primary',
            new_name='is_primary',
        ),
    ]
